SELECT * FROM fabricante;
SELECT * FROM producto;
SELECT nombre FROM producto;
SELECT nombre,precio FROM producto;
SELECT * FROM producto;
SELECT nombre, ROUND(precio) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT codigo_fabricante,COUNT(codigo_fabricante) AS'Total Prod' FROM producto GROUP BY codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre, precio FROM producto ORDER BY nombre,precio ASC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM producto ORDER BY precio LIMIT 1;
SELECT * FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre, precio FROM producto WHERE precio <= 120;
SELECT nombre,precio FROM producto WHERE precio BETWEEN 60 AND 200;
SELECT nombre,codigo_fabricante FROM producto WHERE codigo_fabricante IN (1,2,3);
SELECT nombre, precio FROM producto WHERE nombre LIKE '%portatil%';
SELECT producto.codigo AS 'Codigo Prod',fabricante.codigo AS 'Codigo Fabr',fabricante.nombre,producto.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY p.nombre;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY precio LIMIT 1;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'lenovo';
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Crucial' AND precio > 200;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre IN ('asus', 'hewlett-packard');
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE precio >= 180 ORDER BY precio ASC,p.nombre ASC;
SELECT COUNT(codigo_fabricante) AS PRODUCTOS,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante GROUP BY f.nombre ORDER BY f.nombre;
SELECT COUNT(codigo_fabricante) AS PRODUCTOS,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante GROUP BY f.nombre HAVING (COUNT(codigo_fabricante)) = 0 ORDER BY f.nombre;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'lenovo';
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE precio >= (SELECT MAX(precio) from producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'lenovo' );
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'lenovo' LIMIT 1;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'asus' AND precio < (SELECT AVG(precio) FROM producto);
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IN (1,2,3,4,5,6,7,8,9);
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.codigo NOT IN (1,2,3,4,5,6,7);
SELECT COUNT(codigo_fabricante) AS PRODUCTOS,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante GROUP BY f.nombre HAVING (COUNT(codigo_fabricante)) = (SELECT COUNT(codigo_fabricante) FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'lenovo' GROUP BY f.nombre) ORDER BY f.nombre;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE p.nombre IS NULL;
SELECT p.nombre AS 'Nombre Prod',precio,f.nombre AS 'Nombre Fabr' FROM producto p RIGHT JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE p.nombre IS NOT NULL;